name: Format and Push

on:
    pull_request:
        branches: ['*']

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT_SESCRET }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Prettier globally
              run: npm install -g prettier

            - name: Run Prettier
              run: prettier --write "**/*.{ts,tsx}"

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit and Push if Needed
              id: push_changes
              run: |
                  git add .
                  if git diff --cached --quiet; then
                    echo "No formatting changes."
                    echo "changed=false" >> $GITHUB_OUTPUT
                  else
                    git commit -m "chore: auto-format code with Prettier"
                    git push
                    echo "changed=true" >> $GITHUB_OUTPUT
                  fi

            - name: Comment on PR
              if: steps.push_changes.outputs.changed == 'true'
              uses: peter-evans/create-or-update-comment@v4
              with:
                  token: ${{ secrets.PAT_SESCRET }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ✅ El código fue auto-formateado automáticamente con **Prettier** y se ha hecho un push con los cambios.
